# Funding links for wolai-mcp
# These are displayed as a "Sponsor" button on the GitHub repo

custom:
  - https://afdian.com/a/LittlePeter52012
  - https://etherscan.io/address/0xD42c7c40785Fc00C707B859C541d42037611843b
